#spring:
#  dubbo:
#    application:
#      name: dubbo-provider
#    registry:
#      address: zookeeper://192.168.1.59:2181
#    protocol:
#      name: dubbo
#      port: 20880
#    scan: com.yangkai.service